<?php
  function post_module_theme($existing, $type, $theme, $path) {
    return [
      'post_template' => [
        'variables' => ['test_var' => NULL],
      ],
      'show_template' => [
        'variables' => ['data' => NULL],
      ],
      'result_template' => [
        'variables' => [
          'articles' => [],
          'tags' => NULL,
        ],
      ],
      'tags_block' => [
        'variables' => [
          'tags' => NULL,
        ],
      ],
      'descriptionsection_block' => [
        'variables' => ['title' => NULL, 'logs' => NULL],
        'template' => 'block--descriptionsection',
      ],
    ];
  }
function post_module_page_attachments(array &$page)
{
  $routeName = \Drupal::routeMatch()->getRouteName();
  $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();
  if ($routeName == 'post_module.search')
    $page['#attached']['library'][] = 'post_module/post-search';
    $page['#attached']['drupalSettings']['defaultLang'] = $lang;

}

?>
